name = "mcc2"
workers_dev = true
kv_namespaces = [
	{ binding = "MCC2", id = "23da573f09ee42e3be72cd0d8726e224", preview_id = "9b4eb7c58f8245beb711994ee97cc1e2" },
]
compatibility_date = "2022-07-07"
